spring:
  application:
    name: auth-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth
    username: user
    password: password

server:
  port: 9090

jwt:
  issuer: kerry
  subject: auth
  expiration: 3600
  secretKey: 12345678901234567890123456789012